import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
// import { AIService } from 'src/app/core/services/ai.service';

@Component({
  selector: 'app-letter',
  templateUrl: './letter.component.html',
  styleUrls: ['./letter.component.scss']
})
export class LetterComponent implements OnInit {

  letterForm: FormGroup;
  generatedLetter = 'Your generated cover letter will appear here...';
  isLoading = false;

  constructor(
    private fb: FormBuilder,
    // private aiService: AIService
  ) { }

  ngOnInit(): void {
    this.letterForm = this.fb.group({
      jobDescription: [''],
      cvId: [null] // To select which CV to use
    });
  }

  generateLetter() {
    if (this.letterForm.invalid) {
      return;
    }
    this.isLoading = true;
    console.log('Generating letter with data:', this.letterForm.value);
    // this.aiService.generateCoverLetter(this.letterForm.value).subscribe(response => {
    //   this.generatedLetter = response.letter;
    //   this.isLoading = false;
    // });
    setTimeout(() => {
      this.generatedLetter = 'This is a sample cover letter generated by the AI based on the job description and your selected CV. It highlights your key skills and experiences relevant to the role...';
      this.isLoading = false;
    }, 1500);
  }
}
